version: "3.8"

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    env_file:
      - ./frontend/.env

  backend:
    build: ./backend
    ports:
      - "3001:3001"
    depends_on:
      - mongo
    env_file:
      - ./backend/.env

  analyzer:
    build: ./analyzer
    depends_on:
      - mongo
    env_file:
      - ./analyzer/.env

  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
