services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=${VITE_API_URL}
    ports:
      - "${FRONTEND_HOST_PORT}:${FRONTEND_CONTAINER_PORT}"
    depends_on:
      - backend
    env_file:
      - ./frontend/.env

  backend:
    build: ./backend
    ports:
      - "${BACKEND_HOST_PORT}:${BACKEND_CONTAINER_PORT}"
    depends_on:
      - mongo
    env_file:
      - ./backend/.env

  analyzer:
    build: 
      context: ./analyzer
      dockerfile: Dockerfile
    ports:
      - "${APIFLASK_HOST_PORT}:${APIFLASK_CONTAINER_PORT}"
    depends_on:
      - mongo
    env_file:
      - ./analyzer/.env

  mongo:
    image: mongo:6
    ports:
      - "${MONGO_HOST_PORT}:${MONGO_CONTAINER_PORT}"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
